name: Eric L Anderson.com
description: thoughts, ramblings, etc
markdown: redcarpet
pygments: true
permalink: /entries/:title
paginate: 5
paginate_path: "/entries/page/:num"
include: ['.well-known']

redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'strikethrough', 'superscript', 'smart']
